name: Build and Deploy HelpDesk App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Install Backend Production Dependencies
        run: |
          cd server
          npm install
      
      - name: Deploy files with rsync
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Sincroniza los archivos. -a preserva permisos, -v es verboso, --delete elimina archivos viejos.
            # Se excluye la carpeta node_modules del cliente y el .git para no transferirlos.
            rsync -av --delete --exclude 'client/node_modules' --exclude '.git' $GITHUB_WORKSPACE/ /var/www/helpdesk_app/
            
            # Reinicia el servicio
            echo "Restarting application..."
            sudo systemctl restart helpdesk-api.service
            echo "Deployment finished!"